# Generated by Django 5.2.1 on 2025-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_user_otp_code_remove_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
