# Generated by Django 5.2.1 on 2025-05-11 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '010' or '+2010' and be 11 digits long (13 with +20). Example: '01012345678' or '+201012345678'", regex='^(?:\\+20|0)10[0-9]{8}$')], verbose_name='phone'),
        ),
    ]
